name: test

on:
  push

jobs:
 combine-yaml:
  runs-on: ubuntu-latest
  steps:
  - uses: actions/checkout@v4
  - name: Parse YAML
    run: |
      yq --version
      ls
      cd ${{ GITHUB.WORKSPACE }}
      ls
      yq -n 'load("${{ GITHUB.WORKSPACE }}/file1.yaml") * load("${{ GITHUB.WORKSPACE }}/file2.yaml")'
  # - name: yq - portable yaml processor
  #   uses: mikefarah/yq@v4.47.1
  #   run: |
  #     cd ${{ GITHUB.WORKSPACE }}
  #     yq -n 'load("file1.yaml") * load("file2.yaml")'