name: test

on:
  push

jobs:
 combine-yaml:
  runs-on: ubuntu-latest
  steps:
  - name: Parse YAML
    run: |
    yq --version
  - name: yq - portable yaml processor
    uses: mikefarah/yq@v4.47.1
    run: |
      cd ${{ GITHUB.WORKSPACE }}
      yq -n 'load("file1.yaml") * load("file2.yaml")'